In [34]:
import numpy as np
from numpy.random import default_rng

In [6]:
sales =  [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
sales_2d_arr = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

sales_2d_arr = np.array(sales_2d_arr)
print(sales_2d_arr)
type(sales_2d_arr)

sales_array = np.array(sales)
print(sales_array)
type(sales_array)


[[   0    5  155    0  518]
 [   0 1827  616  317  325]]
[   0    5  155    0  518    0 1827  616  317  325]


numpy.ndarray

In [5]:
print(np.ndim(sales_array))
print(np.shape(sales_array))
print(np.size(sales_array))

1
(10,)
10


In [12]:
array = np.array(range(5))
print(array)

# array_2d = np.array(range(10)).reshape(2, 5)
array_2d = np.array([range(6), range(6)])
print(array_2d)

[0 1 2 3 4]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [16]:
array_2d.T
array.T.shape

(5,)

In [24]:
my_list = [x**2 for x in range(1, 6)]
print(my_list)

array = np.array(my_list).reshape(5)
print(array)

np.arange(10)

[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.ones(5)
np.zeros(100, int).reshape(10, 10)
np.linspace(0, 99, 10)

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [35]:
rng = default_rng(12345)
random_array = rng.random(10)
print(random_array)

[0.22733602 0.31675834 0.79736546 0.67625467 0.39110955 0.33281393
 0.59830875 0.18673419 0.67275604 0.94180287]


In [40]:
fruits = ["apples", "oranges", "bananas", "pinaples"]
print(fruits[:2])
print(fruits[2:])
print(fruits[1:3])
print(fruits[::3])

['apples', 'oranges']
['bananas', 'pinaples']
['oranges', 'bananas']
['apples', 'pinaples']


In [50]:
my_array_num = np.array([np.arange(15)]).reshape(3, 5)
print(my_array_num)
print("---" * 10)
print(my_array_num[1:, :])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------------------------
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [64]:
random_array = np.random.randint(0, 10, size=5)
np.array(random_array)

array([7, 4, 2, 9, 0])

In [69]:
my_array_num % 2 == 0

my_array_num[my_array_num % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [67]:
np.where(my_array_num % 2 == 0, "even", "odd")

array([['even', 'odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd', 'even']], dtype='<U4')

In [74]:
sum_array = sales_array.sum
print(sum_array)

<built-in method sum of numpy.ndarray object at 0x783e03d1d2f0>


In [77]:
print(np.median(sales_array))
print(np.mean(sales_array))
print(np.std(sales_array))

236.0
376.3
529.1366647662965


In [13]:
import pandas as pd

data = [10, 20, 30, 40, 50]
items = ["coffee", "shoes", "clothes", "phone", "laptop"]

#s = pd.Series(data).astype("float")
s = pd.Series(data, index=items, name="Sales")
print(s)

# Corrected: Use square brackets and a single index for a Series
position = s.iloc[4]
print("____"*10)
print(position)

print("____"*10)

item_position = s.loc["laptop"]
print(item_position)

item_index = s.index[3], int(s.iloc[3])
print("____"*10)
print(item_index)

print("____"*10)

s.mean()
s.median()
s.std()

coffee     10
shoes      20
clothes    30
phone      40
laptop     50
Name: Sales, dtype: int64
________________________________________
50
________________________________________
50
________________________________________
('phone', 40)
________________________________________


15.811388300841896